[package]
name = "buzz-rust"
version = "0.1.0"
authors = ["rdettai <contact@cloudfuse.io>"]
edition = "2018"
build = "build.rs"

[lib]
name = "buzz"

[[bin]]
name = "lambda"
path = "src/bin/main_lambda.rs"

[[bin]]
name = "hive"
path = "src/bin/main_hive.rs"

[[bin]]
name = "bee"
path = "src/bin/main_bee.rs"


[dependencies]
arrow = { git = "https://github.com/apache/arrow", rev = "68866a1e", feature=["prettyprint"] }
parquet = { git = "https://github.com/apache/arrow", rev = "68866a1e" }
datafusion = { git = "https://github.com/apache/arrow", rev = "68866a1e" }
arrow-flight = { git = "https://github.com/apache/arrow", rev = "68866a1e" }
tokio = { version = "0.2", features = ["macros", "rt-core", "rt-threaded"] }
rusoto_core = { version = "0.45.0", default_features = false, features=["rustls"] }
rusoto_s3 = { version = "0.45.0", default_features = false, features=["rustls"] }
async-trait = "0.1"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lambda_runtime = "0.2.1"
tonic = "0.3"
pin-project = "1.0"
snafu = "0.6.9"
prost = "0.6"
prost-types = "0.6"

[build-dependencies]
prost-build = { version = "0.6.1" }