version: '2.4'

services:
  hive:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: runtime-stage
      args: 
        BIN_NAME: flight_server
    environment: 
      - RUST_BACKTRACE=1
    ports:
      - 50051

  bee:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: runtime-stage
      args: 
        BIN_NAME: flight_client
    cpus: 2
    mem_limit: 2048M
    environment: 
      - RUST_BACKTRACE=1
    scale: 3
    depends_on:
      - hive

