version: '2.4'

services:
  fuse:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: runtime-stage
      args: 
        BIN_NAME: fuse_local
    environment: 
      - RUST_BACKTRACE=1
    depends_on:
      - hcomb
      - hbee

  hcomb:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: runtime-stage
      args: 
        BIN_NAME: hcomb
        PORT: 3333
    environment: 
      - RUST_BACKTRACE=1
    mem_limit: 4096M
    cpus: 4
    ports:
      - 3333
    # scale: 1

  hbee:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: runtime-stage
      args: 
        BIN_NAME: hbee_local
        PORT: 3000
    volumes:
      - ~/.aws/credentials:/.aws/credentials
    environment: 
      - AWS_SHARED_CREDENTIALS_FILE=/.aws/credentials
      - AWS_PROFILE
      - RUST_BACKTRACE=1
    mem_limit: 2048M
    cpus: 2
    ports:
      - 3000
    # scale: 1

