name: Codecov

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Tarpaulin
      working-directory: ./code
      run: cargo install cargo-tarpaulin --version 0.18.0
    - name: Run Tarpaulin
      working-directory: ./code
      run: cargo tarpaulin --out Xml
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v2
      with:
        working-directory: ./code

