name: Codecov

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      working-directory: ./code
      with:
        version: '0.18.0'
        args: '-- --test-threads 1'
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v2
      working-directory: ./code
